### ISSUE TITLE
ECS Support

### ISSUE THREAD

**Issue by challgren** [cakephp/cakephp-codesniffer#389]
My company has recently been switching over to ECS https://github.com/easy-coding-standard/easy-coding-standard for our coding standards and automatic rector rules. I was wondering if it's on the roadmap to support ECS? Since I'm in the process of migrating I could write the CakePHPSet and convert the phpcs.xml to ecs. But this would introduce having to maintain duplicate codes because they both follow the same format just in different ways. I wouldn't be able to help write a convertor but I think that would be the easiest forward. Just opening up a discussion on this since ECS and rector along with this repo have kept my code clean and developers from introducing older coding styles.

**Comment by ADmad** [comment]
There are no plans to switch to / add support for ECS. `phpcs` does its job well  enough and its accompanying binary `phpcbf` autofixes most reported issues. So there's need for us to switch or increase the team's workload by supporting another code formatter.

CakePHP users are welcome to use the tools and standards they like instead of this one.

**Comment by challgren** [comment]
The only change would be converting the ruleset.xml to ecs.php which could easily be maintained going forward. And this would give users the ability to use 1 tool instead of both phpcs and phpcbf as ECS allows fixes to be applied. All the Sniffs and Fixers would be reused by ECS so there wouldn't be duplicate coding. It would just be keep the ruleset.xml and ecs.php in sync.

**Comment by markstory** [comment]
Sounds like work for your company to take on as you're switching to ECS.

**Comment by LordSimal** [comment]
I don't see what real benefit ECS would give us here besides 
- us having to maintain 2 different config files which contain basically the same thing just in a different syntax
- change all our repos to use/support ECS including CI config
- write documentation on what the differences between these 2 tools are and how to use them
- a bigger surface for dependency problems since ECS has a bunch of dependencies in its composer.json

Did I miss something?
